version: "3.8"

# management secret key is NAB5rGwT4qOEB+6nLQawkTfCOV2eiFSjgQK8bfEdZXY=
services:
  fluence-1: # /ip4/127.0.0.1/tcp/9991/ws/p2p/12D3KooWHBG9oaVx4i3vi6c1rSBUm7MLBmyGmmbHoZ23pmjDCnvK
    command: 
      - -f=ed25519
      - -k=29Apzfedhw2Jxh94Jj4rNSmavQ1TkNe8ALYRA7bMegobwp423aLrURxLk32WtXgXHDqoSz7GAT9fQfoMhVd1e5Ww
      - -m=12D3KooWFRgVmb1uWcmCbmJqLr8tBQghL6ysSpK2VyE2VZbaQ6wy
      - -t=7771
      - -w=9991
      - --aqua-pool-size=2
      - --local
    container_name: fluence-1
    environment:
      RUST_BACKTRACE: full
      RUST_LOG: info,network=trace,aquamarine=info,aquamarine::actor=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=info,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,particle_server::behaviour::identify=info,libp2p_mplex=info,libp2p_identify=info,walrus=info,particle_protocol::libp2p_protocol::upgrade=info,kademlia::behaviour=info
      WASM_LOG: info
      FLUENCE_ENV_AQUA_IPFS_EXTERNAL_API_MULTIADDR: /dns4/localhost/tcp/5001
    # image: fluencelabs/rust-peer:ipfs_v0.0.74
    platform: linux/amd64
    build: ./
    ports:
      - 4001:4001   # ipfs swarm
      - 5001:5001   # ipfs rpc
      - 7771:7771   # tcp
      - 9991:9991   # ws
      - 18081:18080 # /metrics
      - 8081:8080 # expose ipfs url
      - 3331:3030 # jsonrpc
    restart: always
    volumes:
      - ./workdir/fluence-1:/.fluence
      - ./jsonrpc:/app/jsonrpc
      - ./ipfs/fluence-1:/config/ipfs
    networks:
      - fluence
    depends_on:
      - rqlite-1

  fluence-2: # /ip4/127.0.0.1/tcp/9992/ws/p2p/12D3KooWRABanQHUn28dxavN9ZS1zZghqoZVAYtFpoN7FdtoGTFv
    command: 
      - -f=ed25519
      - -k=5fNENMwkUT4dW3hPs9ZwqV4qA5pdTtUChTazAx9Awe2Vpz1yaJu3VCmcEZow6YgdFBGoZoFAZUZBbF3c2Ebd2iL
      - -m=12D3KooWFRgVmb1uWcmCbmJqLr8tBQghL6ysSpK2VyE2VZbaQ6wy
      - -t=7772
      - -w=9992
      - --aqua-pool-size=2
      - --bootstraps=/dns/fluence-1/tcp/7771
    container_name: fluence-2
    environment:
      RUST_BACKTRACE: full
      RUST_LOG: info,network=trace,aquamarine=info,aquamarine::actor=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=info,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,particle_server::behaviour::identify=info,libp2p_mplex=info,libp2p_identify=info,walrus=info,particle_protocol::libp2p_protocol::upgrade=info,kademlia::behaviour=info
      WASM_LOG: info
      FLUENCE_ENV_AQUA_IPFS_EXTERNAL_API_MULTIADDR: /dns4/localhost/tcp/5002
    # image: fluencelabs/rust-peer:ipfs_v0.0.74
    platform: linux/amd64
    build: ./
    ports:
      - 4002:4001   # ipfs swarm
      - 5002:5001   # ipfs rpc
      - 7772:7772   # tcp
      - 9992:9992   # ws
      - 18082:18080 # /metrics
      - 8082:8080 # expose ipfs url
      - 3332:3030 # jsonrpc
    restart: always
    volumes:
      - ./workdir/fluence-2:/.fluence
      - ./jsonrpc:/app/jsonrpc
      - ./ipfs/fluence-2:/config/ipfs
    networks:
      - fluence
    depends_on:
      - rqlite-1

  fluence-3: # /ip4/127.0.0.1/tcp/9993/ws/p2p/12D3KooWFpQ7LHxcC9FEBUh3k4nSCC12jBhijJv3gJbi7wsNYzJ5
    command: 
      - -f=ed25519
      - -k=5DTs9LQS8Ay2dM8xBcikDRwYLMcanhsC6tynSSgpLyBZEv5Ey34LVw1fYcCuUj9A9EfvQJB2bsaGhSRoHQ7D6UE5
      - -m=12D3KooWFRgVmb1uWcmCbmJqLr8tBQghL6ysSpK2VyE2VZbaQ6wy
      - -t=7773
      - -w=9993
      - --aqua-pool-size=2
      - --bootstraps=/dns/fluence-1/tcp/7771
    container_name: fluence-3
    environment:
      RUST_BACKTRACE: full
      RUST_LOG: info,network=trace,aquamarine=info,aquamarine::actor=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=info,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,particle_server::behaviour::identify=info,libp2p_mplex=info,libp2p_identify=info,walrus=info,particle_protocol::libp2p_protocol::upgrade=info,kademlia::behaviour=info
      WASM_LOG: info
      FLUENCE_ENV_AQUA_IPFS_EXTERNAL_API_MULTIADDR: /dns4/localhost/tcp/5003
    # image: fluencelabs/rust-peer:ipfs_v0.0.74
    platform: linux/amd64
    build: ./
    ports:
      - 4003:4001   # ipfs swarm
      - 5003:5001   # ipfs rpc
      - 7773:7773   # tcp
      - 9993:9993   # ws
      - 18083:18080 # /metrics
      - 8083:8080 # expose ipfs url
      - 3333:3030 # jsonrpc
    restart: always
    volumes:
      - ./workdir/fluence-3:/.fluence
      - ./jsonrpc:/app/jsonrpc
      - ./ipfs/fluence-3:/config/ipfs
    networks:
      - fluence
    depends_on:
      - rqlite-1

  env.json:
    restart: "no"
    # depends_on:
    #   - fluence
    image: busybox:stable
    volumes:
      - ./workdir/env.json:/env
    command:
      - sh
      - -c
      - |
        cat <<EOF > /env/env.json
        {
            "nodes": [
                {
                    "multiaddr": "/dns4/localhost/tcp/9991/ws/p2p/12D3KooWHBG9oaVx4i3vi6c1rSBUm7MLBmyGmmbHoZ23pmjDCnvK",
                    "peerId": "12D3KooWHBG9oaVx4i3vi6c1rSBUm7MLBmyGmmbHoZ23pmjDCnvK"
                },
                {
                    "multiaddr": "/dns4/localhost/tcp/9992/ws/p2p/12D3KooWRABanQHUn28dxavN9ZS1zZghqoZVAYtFpoN7FdtoGTFv",
                    "peerId": "12D3KooWRABanQHUn28dxavN9ZS1zZghqoZVAYtFpoN7FdtoGTFv"
                },
                {
                    "multiaddr": "/dns4/localhost/tcp/9993/ws/p2p/12D3KooWFpQ7LHxcC9FEBUh3k4nSCC12jBhijJv3gJbi7wsNYzJ5",
                    "peerId": "12D3KooWFpQ7LHxcC9FEBUh3k4nSCC12jBhijJv3gJbi7wsNYzJ5"
                }
            ]
        }
        EOF

  dashboard:
    depends_on:
      - env.json
    image: fluencelabs/dashboard:latest
    volumes:
      - ./workdir/env.json:/dist/env
    networks:
      - fluence
    ports:
      - 8080:8080

  rqlite-1:
    image: rqlite/rqlite:latest
    ports:
      - 4101:4001
      - 4102:4002
    volumes:
      - ./rqlite/rqlite-1:/rqlite/file
    networks:
      - fluence
    command:
      - -on-disk=true
      - -node-id 1
  
  rqlite-2:
    image: rqlite/rqlite:latest
    ports:
      - 4201:4001
      - 4202:4002
    volumes:
      - ./rqlite/rqlite-2:/rqlite/file
    networks:
      - fluence
    depends_on:
      - rqlite-1
    command:
      - -on-disk=true
      - -node-id 2
      - -join http://172.17.0.1:4101
  
  rqlite-3:
    image: rqlite/rqlite:latest
    ports:
      - 4301:4001
      - 4302:4002
    volumes:
      - ./rqlite/rqlite-3:/rqlite/file
    networks:
      - fluence
    depends_on:
      - rqlite-1
    command:
      - -on-disk=true
      - -node-id 3
      - -join http://172.17.0.1:4101

# volumes:
#   fluence: null
#   env.json: null

networks:
  fluence: null
